### ISSUE TITLE
CE 7.1 - Mono Search window disappears after scan

### ISSUE THREAD

**Issue by 7s3** [JasonGoemaat/CheatEngineMonoHelper#2]
Scan of Assembly-CSharp finishes but nothing happens. If I alt+tab, there appears to be a maximized empty window that I can't bring to front.

![explorer_gxZCsgT4uN](https://user-images.githubusercontent.com/4492725/83341082-0589d500-a294-11ea-8fd4-0d95d3b99932.png)

**Comment by Acen** [comment]
Have found this happening too.
Windows 10 Pro, x64. CE 7.1

**Comment by JasonGoemaat** [comment]
I haven't run into the issue...   Sorry for the late response, there have been a lot of changes and the current version requires 7.5 I think (using it on 7.5.2) due to a couple of changes in CE's monoscript.lua.   Can you try the new version?   Just download the 'Dev.CT' file and use the 'MonoHelper' table entry.
